# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: 519fall2023-project-prisnguyen
  WEBAPP_PACKAGE_PATH: 'Node/WEB'
  FRONTEND_PACKAGE_PATH: 'Node/WEB/frontend'
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './Node/WEB/package.json'

      - name: npm install, build, and test
        working-directory: '${{ env.WEBAPP_PACKAGE_PATH }}'
        run: |
          npm install

      - name: npm install react frontend
        working-directory: 'echo ${{ env.FRONTEND_PACKAGE PATH }} and pwd '
        run:
          npm install
          npm run build
          rm -r public
          rm -r node_modules
          rm -r src

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app


      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.WEBAPP519FALL2023-PROJECT-PRISNGUYEN }}
          package: ${{ env.WEBAPP_PACKAGE_PATH }}
