name: Trigger auto deployment for spring2024-hw02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spring2024-hw02-AutoDeployTrigger-1ba0a144-1025-4752-bd93-8d0f6370fd85.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRING2024HW02_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRING2024HW02_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRING2024HW02_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cs519spring2024.azurecr.io
          registryUsername: ${{ secrets.SPRING2024HW02_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRING2024HW02_REGISTRY_PASSWORD }}
          containerAppName: spring2024-hw02
          resourceGroup: container-app
          imageToBuild: cs519spring2024.azurecr.io/spring2024-hw02:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


